### PR TITLE
Fix rest parameters with array and objects

### LINKED ISSUE #53: Allow Array as Rest Parameter Target in Arguments
``` js
((...[, y, z]) => console.log(y, z))(1, 2, 3);
```

> However, this code is valid in ES2016. It even works in Chrome 50.
> For more information, see https://esdiscuss.org/topic/ignoring-arguments

https://phabricator.babeljs.io/T7396

### LINKED ISSUE #308: incorrect pattern parsing in array rest
### Input Code

```js
var [...{length}] = [ 1, 2, 3];
console.log(y);
```

### Babylon/Babel Configuration

presets - latest

### Expected Behavior

```
→ ./out.gn/x64.debug/d8 -e "var [...{length}] = [1, 2, 3]; print(length);"
3
```

### Current Behavior

SyntaxError

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  
| node             | 
| npm              | 
| Operating System |

### PR DESCRIPTION
**Pull request by existentialism**
| Q                 | A
| ----------------- | --
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes/yes
| Fixed tickets     | Fixes #53, Fixes #308
| License           | MIT

May have gone overkill with the tests, but added rest parameter-related esprima and test262 fixtures.

Ref: https://github.com/babel/babylon/commit/9e264e70ae483917d694c4840392d34327d1b12f

### CODE REVIEW

**Comment by hzoo** [comment]
Hey @existentialism! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/213868578)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/213868579)

File: src/parser/lval.js [hunk 1]
```diff
@@ -123,14 +123,11 @@ pp.parseBindingIdentifier = function () {
...
 // Parses lvalue (assignable) atom.
-
 pp.parseBindingAtom = function () {
   switch (this.state.type) {
     case tt._yield:
-      if (this.state.strict || this.state.inGenerator) this.unexpected();
-      // fall-through
     case tt.name:
-      return this.parseIdentifier(true);
+      return this.parseIdentifier(this.shouldAllowYieldIdentifier());
```
Comment (danez) [inline src/parser/lval.js]: Could do parseBindingIdentifier() here?

File: src/parser/lval.js [hunk 2]
```diff
@@ -123,14 +123,11 @@ pp.parseBindingIdentifier = function () {
 };
 
 // Parses lvalue (assignable) atom.
-
 pp.parseBindingAtom = function () {
   switch (this.state.type) {
     case tt._yield:
-      if (this.state.strict || this.state.inGenerator) this.unexpected();
```
Comment (danez) [inline src/parser/lval.js]: This is not necessary?

**Comment by hzoo** [comment]
Hey @existentialism! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/213868578)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/213868579)

File: src/parser/lval.js (hunk 2 above)
Comment (existentialism) [inline src/parser/lval.js]: There's another check inside `parseIdentifier/shouldAllowYieldIdentifier` via `checkReservedWord`.

Can revert it needed?

File: src/parser/lval.js (hunk 1 above)
Comment (existentialism) [inline src/parser/lval.js]: Updated!

**Comment by hzoo** [comment]
Hey @existentialism! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/214422949)
* [Node vlts/* - linux](https://travis-ci.org/babel/babylon/jobs/214422951)

File: src/parser/lval.js (hunk 2 above)
Comment (danez) [inline src/parser/lval.js]: Yes I was just worried because I couldn't find a check for isGenerator but I see now that when it is a generator it will check for keywords inside parseIdentifier()
