### PR TITLE
Fix function.sent parsing

### LINKED ISSUE #611: function.sent as an expression statement.
### Input Code

```js
function* gen() {
  (function.sent);
  function.sent;
}
```

### Babylon/Babel Configuration

```js
{
  "plugins": [ "functionSent" ]
}
```

### Expected Behavior
The second and third lines should be parsed in the same way.

Ref: https://github.com/allenwb/ESideas/issues/13#issuecomment-313559409

### Current Behavior
The third lines throws something like "Unexpected ."

https://astexplorer.net/#/gist/5d4d44becbe4b3236be7a2a2f8b9e81c/latest

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.16

### LINKED ISSUE #612: Dot after "function" inside a generator doesn't throw
### Input Code

```js
function* foo() {
  (function.fn() {});
}
```

https://astexplorer.net/#/gist/4a6290c9416046ef323f5cef1202e28f/latest

### Babylon/Babel Configuration

The `functionSent` plugin must be disabled.

### Expected Behavior

It should throw

### Current Behavior

The dot is ignored

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.16

### PR DESCRIPTION
**Pull request by jridgewell**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | Fixes #611, Fixes #612
| License           | MIT

Fixes `function.sent` parsing.

### CODE REVIEW

File: src/parser/statement.js [hunk 1]
```diff
@@ -94,6 +94,7 @@ export default class StatementParser extends ExpressionParser {
       case tt._for:
         return this.parseForStatement(node);
       case tt._function:
+        if (this.lookahead().type === tt.dot) break;
         if (!declaration) this.unexpected();
```
Comment (nicolo-ribaudo) [inline src/parser/statement.js]: Maybe you can add a test which checks the order of these two conditions.

e.g.
```js
function* gen() {
  if (true) function.sent;
}
```

Comment (jridgewell) [inline src/parser/statement.js]: Done.
